DATABASE_USER = 'serveradmin'
USER_PASSWORD = 'TestUnilever1!'
DATABASE_ENDPOINT = 'prdunileverdatabase.mysql.database.azure.com'
DATABASE_SCHEMA = 'transactional_data'

AZURE_DEPLOYMENT = 'gpt-4o-mini'
OPENAI_API_VERSION = '2024-08-01-preview'
AZURE_OPENAI_API_KEY = 'DJSInhXbnuV08lkSHlCihDnQMG2VkZMCdTiCP2l3H4xcushxL88mJQQJ99ALACYeBjFXJ3w3AAABACOGZqoB'
AZURE_OPENAI_ENDPOINT = 'https://unilever-poc-openai.openai.azure.com/openai/deployments/gpt-4o-mini/chat/completions?api-version=2024-08-01-preview'